export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const SET_SPECIFIC_SNIPPIT = 'SET_SPECIFIC_SNIPPIT';
export const ADD_USER = 'ADD_USER';
export const TOGGLE_LANDING_PAGE = 'TOGGLE_LANDING_PAGE';
