export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const SET_SPECIFIC_SNIPPIT = 'SET_SPECIFIC_SNIPPIT';
export const ADD_USER = 'ADD_USER';
export const TOGGLE_LANDING_PAGE = 'TOGGLE_LANDING_PAGE';
export const UPDATE_BOW_AFTER_CREATE = 'UPDATE_BOW_AFTER_CREATE'
export const SET_USER_INFO = 'SET_USER_INFO';
export const SET_USER_INFO_REFRESH = 'SET_USER_INFO_REFRESH';
